name: Android CI

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # 依存関係の出力
    - name: Displays the Android dependencies of the project
      run: ./gradlew androidDependencies
    # ビルド
    - name: Build with Gradle
      run: ./gradlew build
    - name: Compile to APK
      run: ./gradlew assembleDebug

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: app/build/outputs/apk/debug/app-debug.apk
